swagger: '2.0'
info:
  version: '0.1.0'
  title: "[Draft] Store Master Data API"
  description: |
    # Store Master Data API
    Draft of Store Master Data API

produces:
  - application/hal+json      # Representation message format
  # - application/problem+json  # Error message format

schemes:
  - https

securityDefinitions:
   "API Key":
     type: apiKey
     in: header
     name: x-api-key

security:
  - "API Key": []

paths:
  /:
    x-summary: API Root

    get:
      summary: Retrieve API Root
      description: The API Root contains the initial set of link relations.
      responses:
        200:
          description: The root of the API
          schema:
            type: object
            example:
              - _links:
                  self:
                    href: /
            
